# DeepNeed AI 简化版 Docker Compose 配置
version: '3.8'

services:
  # 前端服务 (直接使用当前的简化版本)
  frontend:
    image: node:18-alpine
    container_name: deepneed-frontend-simple
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev --host 0.0.0.0"
    networks:
      - deepneed-network

  # 后端服务 (使用我们创建的最小化后端)
  backend:
    image: python:3.11-slim
    container_name: deepneed-backend-simple
    working_dir: /app
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: sh -c "pip install --break-system-packages fastapi uvicorn httpx pydantic && python3 minimal_backend.py"
    networks:
      - deepneed-network

networks:
  deepneed-network:
    driver: bridge
